package com.meethybridhub.identity;


public enum AuditEventType {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    EMAIL_VERIFIED,
    PASSWORD_RESET_CONFIRMED,
    PASSWORD_CHANGED,
    ROLES_UPDATED,
    USER_STATUS_UPDATED,
    USER_DELETED,
    STORE_CREATED,
    STORE_STATUS_UPDATED,
    PLATFORM_CHARGE_RECORDED,
    STORE_SETTINGS_UPDATED,
    LOGOUT
}
